apiVersion: v1
kind: ConfigMap
metadata:
  name: flaskops-config
  namespace: production
  labels:
    {{- include "flaskops.labels" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.config }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
